### ISSUE TITLE
Missing Tiles in the US/Canada

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#330]
Kind of a #87 problem but this because these tiles timed out. We know exactly which of these tiles are not rendered and will patch them afterward (images can be seen in #251).

The main area that is affected is the US in the area around the big lakes.

<img width="800" alt="map_styles_ _osm2vectortiles" src="https://cloud.githubusercontent.com/assets/1288339/15505737/08ac3790-21c5-11e6-87e9-896d94f8302c.png">

<img width="816" alt="map_styles_ _osm2vectortiles" src="https://cloud.githubusercontent.com/assets/1288339/15505721/f3f8af68-21c4-11e6-9827-4413d9137b4b.png">

**Comment by lukasmartinelli** [comment]
Solved in the newest planet release of **2016-06-13** thanks to the subdivide fix in #352. Thanks @stirringhalo.

**Comment by mnutt** [comment]
I'm still seeing this in the 2016-06-26 update:

![800x800-1](https://cloud.githubusercontent.com/assets/3705/16636139/2e67f9fa-43a4-11e6-9b41-c690020fe78f.png)

(this map is -83.003556,42.27467,10)

**Comment by stirringhalo** [comment]
That is indeed where I was seeing it too. I had one failed tile around lake michigan (and the rest over Antarctica due to zero tiles bug with tilelive-copy #350). I don't have the job handy anymore as I decided to just run with increased timeouts. I will check my second run through.

**Comment by mnutt** [comment]
@lukasmartinelli just wanted to make sure you saw this. Is there a potential fix that I can explore, or is it a matter of extending the timeout?

**Comment by stirringhalo** [comment]
I will be running a new import in the next few days where I've again bumped up the timeouts even further for that one Michigan tile. Hopefully that will resolve this final one.

That one lakes table (I believe it's the Natural-Earth IIRC) wasn't split with the subdivide fix #352 as there were labels in that table that I didn't want to possibly break. So that one table with large features may be to blame.
